version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "medical-convo-summarizer-web"
s3_bucket = "medical-aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "medical-convo-summarizer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = [] 