export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'linear-gradient(to bottom, #ffffff, #f7fafc)',
  },
  header: {
    padding: '1rem',
    backgroundColor: 'white',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    position: 'fixed' as const,
    width: '100%',
    top: 0,
    zIndex: 100,
  },
  headerContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: '#2D3748',
  },
  hero: {
    marginTop: '4rem',
    padding: '6rem 2rem',
    textAlign: 'center' as const,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
  },
  heroContent: {
    maxWidth: '800px',
    margin: '0 auto',
  },
  title: {
    fontSize: '3rem',
    fontWeight: 'bold',
    marginBottom: '1.5rem',
  },
  subtitle: {
    fontSize: '1.25rem',
    lineHeight: '1.8',
    marginBottom: '2rem',
    color: '#E2E8F0',
  },
  button: {
    padding: '1rem 2rem',
    fontSize: '1.125rem',
    fontWeight: 'bold',
    backgroundColor: '#48BB78',
    color: 'white',
    border: 'none',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    transition: 'transform 0.2s, background-color 0.2s',
    '&:hover': {
      backgroundColor: '#38A169',
      transform: 'translateY(-2px)',
    },
  },
  features: {
    padding: '4rem 2rem',
    backgroundColor: 'white',
  },
  featuresGrid: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '2rem',
    padding: '2rem',
  },
  feature: {
    padding: '2rem',
    borderRadius: '0.5rem',
    backgroundColor: 'white',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    transition: 'transform 0.2s',
    '&:hover': {
      transform: 'translateY(-5px)',
    },
  },
  featureIcon: {
    fontSize: '2rem',
    marginBottom: '1rem',
    color: '#4A5568',
  },
  featureTitle: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    color: '#2D3748',
  },
  featureDescription: {
    color: '#4A5568',
    lineHeight: '1.6',
  },
  howItWorks: {
    padding: '4rem 2rem',
    backgroundColor: '#F7FAFC',
  },
  sectionTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    textAlign: 'center' as const,
    marginBottom: '3rem',
    color: '#2D3748',
  },
  steps: {
    maxWidth: '900px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2rem',
  },
  step: {
    display: 'flex',
    alignItems: 'center',
    gap: '2rem',
  },
  stepNumber: {
    width: '3rem',
    height: '3rem',
    borderRadius: '50%',
    backgroundColor: '#667EEA',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '1.25rem',
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    color: '#2D3748',
  },
  stepDescription: {
    color: '#4A5568',
    lineHeight: '1.6',
  },
};
