export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #f7fafc 0%, #e9ecef 100%)",
    display: "flex",
    flexDirection: "column" as const,
  },
  header: {
    padding: "1rem 0",
    backgroundColor: "white",
    boxShadow: "0 2px 8px rgba(44,62,80,0.08)",
    position: "sticky" as const,
    top: 0,
    zIndex: 100,
  },
  headerContent: {
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 1.5rem",
  },
  logo: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "#2D3748",
    letterSpacing: "-1px",
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    background: "#f7fafc",
    borderRadius: "0.5rem",
    padding: "0.5rem 1rem",
    boxShadow: "0 2px 8px rgba(44,62,80,0.04)",
  },
  mainContent: {
    maxWidth: "1200px",
    margin: "2.5rem auto 0 auto",
    padding: "2.5rem 2rem 2rem 2rem",
  },
  welcomeSection: {
    background: "linear-gradient(90deg, #e9ecef 0%, #f7fafc 100%)",
    borderRadius: "1rem",
    padding: "2.5rem 2rem",
    marginBottom: "2.5rem",
    boxShadow: "0 4px 16px rgba(44,62,80,0.08)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
  },
  welcomeTitle: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#2B6CB0",
    marginBottom: "1rem",
    letterSpacing: "-1px",
  },
  recordingSection: {
    background: "white",
    borderRadius: "1rem",
    padding: "2rem 1.5rem",
    marginBottom: "2rem",
    boxShadow: "0 4px 16px rgba(44,62,80,0.08)",
    flex: 1,
    minHeight: "180px",
    display: "flex",
    flexDirection: "column" as const,
  },
  recordingHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  recordingTitle: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    color: "#2D3748",
    letterSpacing: "-0.5px",
  },
  recordingStatus: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "1rem",
    color: "#4A5568",
  },
  statusIndicator: (isRecording: boolean) => ({
    width: "0.75rem",
    height: "0.75rem",
    borderRadius: "50%",
    backgroundColor: isRecording ? "#48BB78" : "#E53E3E",
  }),
  transcriptionContent: {
    background: "#f7fafc",
    borderRadius: "0.5rem",
    padding: "1.5rem",
    marginTop: "1rem",
    maxHeight: "400px",
    overflowY: "auto" as const,
    minHeight: "180px",
    boxShadow: "0 2px 8px rgba(44,62,80,0.04)",
  },
  transcriptionText: {
    whiteSpace: "pre-wrap" as const,
    lineHeight: "1.6",
    color: "#4A5568",
    fontSize: "1.05rem",
  },
  button: {
    padding: "0.85rem 1.5rem",
    fontSize: "1.05rem",
    fontWeight: "bold",
    border: "none",
    borderRadius: "0.5rem",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 2px 8px rgba(49,130,206,0.08)",
  },
  primaryButton: {
    background: "linear-gradient(90deg, #667EEA 0%, #63b3ed 100%)",
    color: "white",
    opacity: 1,
    transition: "opacity 0.2s",
  },
  secondaryButton: {
    backgroundColor: "#E2E8F0",
    color: "#4A5568",
    "&:hover": {
      backgroundColor: "#CBD5E0",
    },
  },
  dangerButton: {
    background: "linear-gradient(90deg, #E53E3E 0%, #F56565 100%)",
    color: "white",
    opacity: 1,
    transition: "opacity 0.2s",
  },
  disabledButton: {
    opacity: 0.5,
    cursor: "not-allowed",
    pointerEvents: "none" as const,
  },
  infoSection: {
    background: "white",
    borderRadius: "1rem",
    padding: "2rem 1.5rem",
    boxShadow: "0 4px 16px rgba(44,62,80,0.08)",
    marginTop: "2rem",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "1.5rem",
    marginTop: "1rem",
  },
  infoCard: {
    padding: "1.5rem",
    background: "#f7fafc",
    borderRadius: "0.5rem",
    border: "1px solid #E2E8F0",
    boxShadow: "0 2px 8px rgba(44,62,80,0.04)",
  },
  infoTitle: {
    fontSize: "1.1rem",
    fontWeight: "bold",
    color: "#2D3748",
    marginBottom: "0.5rem",
  },
  infoText: {
    color: "#4A5568",
    fontSize: "0.95rem",
  },
  sectionsGrid: {
    display: "flex",
    flexDirection: "row" as const,
    gap: "2rem",
    marginBottom: "2rem",
    width: "100%",
    flexWrap: "nowrap" as const,
    alignItems: "stretch",
  },
  sectionColumn: {
    flex: 1,
    minWidth: 0,
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
  },
};
